services:
  fox.users.postgres:
    image: postgres:14-alpine
    container_name: fox.users.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: fox-users
    ports:
      - 5433:5432
    volumes:
      - fox.postgres.users:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fox.users

  fox.users.pgadmin:
    image: dpage/pgadmin4
    container_name: fox.users.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "fox@list.ru"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8083:80
    networks:
      - fox.users

volumes:
  fox.postgres.users:

networks:
  fox.users:
    driver: bridge