version: '3.5'
services:
  betcar.uploader.mongo:
    image: mongo
    restart: always
    container_name: betcar.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: betcar-uploader

    ports:
      - 27018:27017

    volumes:
      - betcar.mongo.uploader:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/betcar-uploader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  betcar.uploader.mongo.ui:
    image: mongo-express
    restart: always
    container_name: betcar.uploader.mongo.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@betcar.uploader.mongo:27017/

volumes:
  betcar.mongo.uploader: